apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loadtest_scenarios/loadtest_scenario_1.yaml
  - loadtest_scenarios/loadtest_scenario_2.yaml

patches:
  - path: worker_patch.yaml
    target:
      kind: LoadTest

namePrefix: kokoro-
