apiVersion: e2etest.grpc.io/v1
kind: LoadTest

metadata:
  name: go-example
  
spec:
  scenariosJSON: |
    {
      "scenarios": [
        {
          "name": "go_example_scenario",
          "warmup_seconds": 5,
          "benchmark_seconds": 30,
          "num_servers": 1,
          "server_config": {
            "async_server_threads": 1,
            "channel_args": [
              {
                "str_value": "latency",
                "name": "grpc.optimization_target"
              }
            ],
            "server_type": "ASYNC_GENERIC_SERVER",
            "payload_config": {
              "bytebuf_params": {
                "resp_size": 0,
                "req_size": 0
              }
            },
            "security_params": null,
            "threads_per_cq": 0,
            "server_processes": 0
          },
          "client_config": {
            "security_params": null,
            "channel_args": [
              {
                "str_value": "latency",
                "name": "grpc.optimization_target"
              }
            ],
            "async_client_threads": 1,
            "outstanding_rpcs_per_channel": 1,
            "rpc_type": "STREAMING",
            "payload_config": {
              "bytebuf_params": {
                "resp_size": 0,
                "req_size": 0
              }
            },
            "client_channels": 1,
            "threads_per_cq": 0,
            "load_params": {
              "closed_loop": {}
            },
            "client_type": "SYNC_CLIENT",
            "histogram_params": {
              "max_possible": 60000000000,
              "resolution": 0.01
            },
            "client_processes": 0
          },
          "num_clients": 1
        }
      ]
    }
