apiVersion: e2etest.grpc.io/v1
kind: LoadTest
metadata:
  name: loadtest-sample
spec:
  driver:
    language: cxx
    run:
      image: debian:stretch
      command: ["/bin/bash"]
      args: ["-c", "sleep", "25m"]
