name: Prettier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Check for Formatting Issues
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for bad extensions
      run: |
        find . | grep ".yml"
        if [ $? -ne 0 ]; then \
          echo "YAML files should use the .yaml extension"; \
        fi
        
    - name: Check prettier for format issues
      run: prettier -c .
